let jsonData = {
  "projectsWithSamples": [
    {
      "projectName": "Gabriel Absorbance",
      "samplesNames": null
    },
    {
      "projectName": "Test 2",
      "samplesNames": [
        "DI water, not fresh",
        "Test 2 for VC (high con.) in DI water",
        "<No sample name>",
        "<No sample name>",
        "1 minute - sample 02",
        "5 min - sample 02",
        "10 minutes - sample 02",
        "1 minute - sample 03",
        "5 minutes - sample 03",
        "20 minutes - sample 02",
        "10 minutes - sample 03",
        "20 min - sample 03",
        "60 minutes - sample 02",
        "60 minutes - sample 03",
        "1 minute - sample 04",
        "10 minutes - sample 04",
        "20 minutes - sample 04",
        "30 minutes - sample 04",
        "60 minutes - sample 04",
        "120 minutes - sample 04",
        "180 minutes - sample 04",
        "5 min with glass",
        "<No sample name>",
        "<No sample name>",
        "min 5, sample 07",
        "10 min, sample 07",
        "20 min, sample 07",
        "5 min, sample 06",
        "min 8, sample 08",
        "min 30, sample 07",
        "min 10, sample 06",
        "min 15, sample 08",
        "min 30, sample 06",
        "min 60, sample 07",
        "min 25, sample 08",
        "min 30, sample 08",
        "min 60, sample 05 with glas",
        "5 min, sample 10",
        "min 7, sample 10",
        "min 10, sample 10",
        "15 min, sample 10",
        "min 16, sample 10",
        "min 17, sample 10",
        "min 18, sample 10",
        "min 20, sample 10",
        "min 30, sample 10",
        "enzyme + water",
        "nr 05 enzyme + water same cuvette",
        "water + enzyme",
        "enzyme + water",
        "VC + Water",
        "VC +water",
        "VC + Water",
        "enzyme + water",
        "enzyme + water",
        "enzyme + water",
        "enzyme + water",
        "Water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water s1",
        "water s1",
        "water s1",
        "water s1",
        "water s1",
        "water + VC",
        "Water + VC",
        "WATER + VC",
        "WATER + VC",
        "WATER + VC TRUE",
        "WATER + VC ",
        "water + vc true",
        "water + vc (water ref. 09)",
        "water + vc (water ref. 09)",
        "water + vc (water ref. 09)",
        "water + vc (water ref. 09)",
        "water + vc (water ref. 09)",
        "water + VC true",
        "Water + VC (water ref 04)",
        "water + VC (water ref 04)",
        "water + VC (water ref 04)",
        "water + VC (water ref 04)",
        "water + VC (water ref 04)",
        "water + VC (same cuvette)",
        "water + VC (same cuvette)",
        "water + VC (same cuvette)",
        "water (same cuvette)",
        "water (same cuvette)",
        "water (same cuvette)",
        "water (same cuvette)",
        "water (same cuvette)",
        "water + VC (same cuvette)",
        "water + 18.75 VC (same cuvette)",
        "water + 18.75 VC (same cuvette)",
        "water (same cuvette)",
        "water (same cuvette)",
        "water + VC (same cuvette)",
        "water (same cuvette)",
        "water (same cuvette)",
        "water + VC (same cuvette)",
        "water + VC (same cuvette)",
        "<No sample name>",
        "<No sample name>",
        "shimatzu water in cuvette nr 6",
        "shimatzu water + VC (12.5 u gram/ml)",
        "Shimadzu water sample scan1",
        "Shimadzu water sample scan nr2",
        "Shimadzu water sample scan3",
        "Shimadzu water sample scan1",
        "Shimadzu water sample scan2",
        "Shimadzu water sample scan1",
        "Shimadzu water sample scan2",
        "Shimadzu water sample",
        "Shimadzu water sample",
        "Shimadzu water sample",
        "Minispec. water sample scan1",
        "Minispec. water sample scan2",
        "Minispec. water sample scan3",
        "Minispec. water sample scan1",
        "Minispec. water sample scan2",
        "Minispec. water sample scan1",
        "Minispec. water sample scan2",
        "Minispec. water sample scan1",
        "Minispec. water sample scan2",
        "Minispec. water + 1.1ug VC",
        "Minispec. water + 5.5ug VC",
        "Minispec. water + 120 ug VC",
        "Shimadzu Water + 1.1 ug VC",
        "Shimadzu water + 5.5 ug VC",
        "Shimadzu water + 120 ug VC",
        "minispectro water at 1000 scan1 ",
        "minispectro water at 1000 scan2",
        "minispectro water at 1000 scan3",
        "minispectro water at 1000 scan1",
        "minispectro water at 1000 scan2",
        "minispectro water at 1000 scan3",
        "minispectro water at 1000 nr of scan 30 scan1",
        "minispectro water at 1000 nr of scan 30 scan2",
        "minispectro water at 1000, nr of scan 30 scan3",
        "minis water + VC at 1000, nr of scan 30, Concentration 120 ug/l",
        "minis water at 1000, nr of scan 30",
        "minis water + VC at 1000, nr of scan 30, Concentration 5.5 ug/l",
        "water from Cleanroom scan1",
        "water from Cleanroom scan2",
        "water from Cleanroom scan3",
        "water2 from Cleanroom scan1",
        "water2 from Cleanroom scan2",
        "water2 from Cleanroom scan3",
        "water2 from Cleanroom + 120 ug VC/liter",
        "water from Cleanroom scan1",
        "water from Cleanroom scan2",
        "water from Cleanroom scan3",
        "water from Cleanroom + 120 ug VC/liter",
        "water from Cleanroom",
        "water from Cleanroom + 240 ug VC/liter",
        "water from Cleanroom scan1",
        "water from Cleanroom + 240 ug VC/liter",
        "water from Cleanroom scan1",
        "water from Cleanroom scan1",
        "water from Cleanroom scan2",
        "water from Cleanroom scan3",
        "water2 from Cleanroom scan1",
        "water2 from Cleanroom + 240 ug VC /liter",
        "water2 from Cleanroom + 360 ug VC/liter",
        "water new batch",
        "water new batch",
        "water new batch",
        "water new batch + VC (120 ug/ 1000 ml)",
        "water new batch + VC (120 ug/ 1000 ml)",
        "water new batch",
        "water new batch + VC (120 ug/ 1000 ml)",
        "water new batch",
        "water new batch + VC (120 ug/ 1000 ml)",
        "water new batch",
        "water new batch + VC (120 ug/ 1000 ml)",
        "water new batch",
        "water new batch + VC (120 x 20 ug/ 1000 ml)",
        "water new batch",
        "water new batch",
        "water new batch + VC (120 x 20 ug/ 1000 ml)",
        "water new batch",
        "water new batch ",
        "water new batch + VC (120 x 20 ug/ 1000 ml)",
        "water new batch",
        "water new batch + VC (120 x 20 ug/ 1000 ml)",
        "water new batch",
        "water new batch + VC (120 x 20 ug/ 1000 ml)",
        "water new batch",
        "water + enzyme",
        "water new batch",
        "water + enzyme",
        "water sample",
        "water sample",
        "water sample",
        "water sample",
        "water sample",
        "water sample",
        "water sample",
        "water sample medium",
        "water sample",
        "water sample",
        "water sample",
        "water + enzyme 1",
        "water + enzyme 2",
        "water + enzyme 3",
        "water + enzyme 4",
        "water + enzyme 5",
        "water + enzyme 6",
        "water + enzyme 7",
        "water + enzyme 8",
        "water + enzyme 9",
        "water + enzyme 10",
        "water + enzyme 11",
        "water + enzyme 12",
        "water + enzyme 13",
        "water + enzyme 14",
        "water + VC ",
        "water + VC 2",
        "water + VC 3",
        "water + VC 4",
        "water + VC 5",
        "water + VC 6",
        "water + VC 7",
        "water + VC 8",
        "water + VC 9",
        "water + VC 10",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "Water + VC + Enzyme",
        "Water + VC + Enzyme",
        "Water + VC + Enzyme",
        "Water + VC + Enzyme",
        "Water + VC + Enzyme",
        "Water + VC + Enzyme",
        "Water + VC + Enzyme",
        "Water + VC + Enzyme",
        "Water + VC + Enzyme",
        "Water + VC + Enzyme",
        "Water + VC + Enzyme",
        "Water + VC + Enzyme",
        "Water + VC + enzyme 1 new batch ",
        "Water + VC + enzyme 2 new batch ",
        "Water + VC + enzyme 3 new batch ",
        "Water + VC + enzyme 4 new batch ",
        "Water + VC + enzyme 5 new batch ",
        "Water + VC + enzyme 6 new batch ",
        "Water + VC + enzyme 7 new batch ",
        "Water + VC + enzyme 8 new batch ",
        "Water + VC + enzyme 9 new batch ",
        "Water + VC + enzyme 10 new batch ",
        "water- cuvette nr1",
        "water- cuvette nr1",
        "water- cuvette nr2",
        "water- cuvette nr2",
        "water- cuvette nr3",
        "water- cuvette nr3",
        "water- cuvette nr4",
        "water- cuvette nr4",
        "water- cuvette nr5",
        "water- cuvette nr5",
        "water- cuvette nr6",
        "water- cuvette nr6",
        "water- cuvette nr7",
        "water- cuvette nr7",
        "water- cuvette nr8",
        "water- cuvette nr8",
        "water- cuvette nr9",
        "water- cuvette nr9",
        "water- cuvette nr9",
        "water- cuvette nr10",
        "water- cuvette nr10",
        "water + VC 120 ug vc/l",
        "water + VC 120 ug vc/l",
        "water + VC 120 ug vc/l",
        "water + VC 120 ug vc/l",
        "water + VC 120 ug vc/l",
        "water + VC 120 ug vc/l",
        "water + VC 120 ug vc/l",
        "water + VC 120 ug vc/l",
        "water + VC 120 ug vc/l",
        "water + VC 120 ug vc/l",
        "water + enzyme 2.5mg/100ml",
        "water + enzyme 2.5mg/100ml",
        "water + enzyme 2.5mg/100ml",
        "water + enzyme 2.5mg/100ml",
        "water + enzyme 2.5mg/100ml",
        "water + enzyme 2.5mg/100ml",
        "water + enzyme 2.5mg/100ml",
        "water + enzyme 2.5mg/100ml",
        "water + enzyme 2.5mg/100ml",
        "water + enzyme 2.5mg/100ml",
        "water + enzyme 2.5mg/100ml + VC ",
        "water + enzyme 2.5mg/100ml + VC ",
        "water + enzyme 2.5mg/100ml + VC ",
        "water + enzyme 2.5mg/100ml + VC ",
        "water + enzyme 2.5mg/100ml + VC ",
        "water + enzyme 2.5mg/100ml + VC ",
        "water + enzyme 2.5mg/100ml + VC ",
        "water + enzyme 2.5mg/100ml + VC ",
        "water + enzyme 2.5mg/100ml + VC ",
        "water + enzyme 2.5mg/100ml + VC ",
        "WATER",
        "WATER 270 - 100",
        "water 289 - 50",
        "water 289 - 50",
        "Water + VC 120ug/liter",
        "water 289 - 50",
        "water 289 - 50",
        "water 289 - 50",
        "water 580 - 25",
        "water 250 - 60",
        "water 150 - 100",
        "water 289 - 50",
        "water 289 - 50 not good",
        "water 289 - 50",
        "water 289 - 50",
        "water 289 - 50 not good",
        "water 289 - 50",
        "water 289 - 50",
        "water 289 - 50",
        "water 289 - 50",
        "water 289 - 50",
        "water 289 - 50",
        "water 289 - 50",
        "solution: water + enzyme + VC ",
        "solution: water + enzyme + VC ",
        "solution: water + enzyme + VC ",
        "solution: water + enzyme + VC ",
        "solution: water + enzyme + VC ",
        "solution: water + enzyme + VC ",
        "solution: water + enzyme + VC ",
        "solution: water + enzyme + VC ",
        "solution: water + enzyme + VC ",
        "water 2- after wash",
        "water 2- after wash",
        "water 2- after wash",
        "water 2- after wash",
        "water 2- after wash",
        "water 2- after wash",
        "water 2- after wash",
        "water 2- after wash",
        "water 2- after wash",
        "water 2- after wash",
        "water 2- after wash",
        "solution 2: water + enzyme + VC ",
        "solution 2: water + enzyme + VC ",
        "solution 2: water + enzyme + VC ",
        "solution 2: water + enzyme + VC ",
        "solution 2: water + enzyme + VC ",
        "solution 2: water + enzyme + VC ",
        "solution 2: water + enzyme + VC ",
        "solution 2: water + enzyme + VC ",
        "solution 2: water + enzyme + VC ",
        "solution 2: water + enzyme + VC ",
        "sample 698 - 11213 - first",
        "sample 698 - 11213 - second",
        "sample 698 - 11212 - first",
        "sample 698 - 11212 - second",
        "sample 698 - 11214 - first",
        "sample 698 - 11214 - second",
        "water 289 - 50",
        "water 289 - 50",
        "water 289 - 50",
        "water + VC (120ug/L) 289 - 50",
        "water + VC (120ug/L) 289 - 50",
        "water + VC (120ug/L) 289 - 50",
        "water + VC (120ug/L) 289 - 50",
        "water + VC (120ug/L) 289 - 50",
        "water + VC (120ug/L) 289 - 50"
      ]
    },
    {
      "projectName": "VC detection (for 120 \u03bcg per liter concentration)",
      "samplesNames": [
        "water with settings: 289 - 50",
        "water with settings: 289 - 50",
        "water with settings: 289 - 50",
        "water with settings: 289 - 50",
        "water with settings: 289 - 50",
        "water with settings: 289 - 50",
        "water with settings: 289 - 50",
        "water with settings: 289 - 50",
        "water with settings: 289 - 50",
        "water with settings: 289 - 50",
        "water + VC with settings: 289 - 50",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (selecting reference file)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)",
        "water + VC (new sample)"
      ]
    },
    {
      "projectName": "Environmental Sample",
      "samplesNames": [
        "Water",
        "Water",
        "sample 11212",
        "Water",
        "Water",
        "Sample 11212",
        "water",
        "water",
        "Sample 11213",
        "water",
        "water",
        "Sample 112113",
        "Water",
        "water",
        "Sample 11214",
        "water",
        "Sample 11214"
      ]
    },
    {
      "projectName": "VC detection (for 5,5 \u03bcg per liter concentration)",
      "samplesNames": [
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC"
      ]
    },
    {
      "projectName": "5,5 ug of VC per ml of water",
      "samplesNames": [
        "water + VC",
        "water",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC"
      ]
    },
    {
      "projectName": "Enzyme + VC + Water 08.04.2022",
      "samplesNames": [
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "1 ug VC + 0,18 mg of enzyme / 100 ml",
        "1 ug VC + 0,18 mg of enzyme / 100 ml",
        "1 ug VC + 0,18 mg of enzyme / 100 ml",
        "1 ug VC + 0,18 mg of enzyme / 100 ml",
        "1 ug VC + 0,18 mg of enzyme / 100 ml",
        "1 ug VC + 0,18 mg of enzyme / 100 ml",
        "1 ug VC + 0,18 mg of enzyme / 100 ml",
        "1 ug VC + 0,18 mg of enzyme / 100 ml",
        "water",
        "1 ug VC + 0,18 mg of enzyme / 100 ml",
        "1 ug VC + 0,18 mg of enzyme / 100 ml",
        "1 ug VC + 0,18 mg of enzyme / 100 ml",
        "1 ug VC + 0,18 mg of enzyme / 100 ml",
        "1 ug VC + 0,18 mg of enzyme / 100 ml",
        "1 ug VC + 0,18 mg of enzyme / 100 ml",
        "1 ug VC + 0,18 mg of enzyme / 100 ml",
        "1 ug VC + 0,18 mg of enzyme / 100 ml",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "10 ug VC + 1,8 mg of enzyme / 100 ml",
        "10 ug VC + 1,8 mg of enzyme / 100 ml",
        "10 ug VC + 1,8 mg of enzyme / 100 ml",
        "10 ug VC + 1,8 mg of enzyme / 100 ml",
        "10 ug VC + 1,8 mg of enzyme / 100 ml",
        "10 ug VC + 1,8 mg of enzyme / 100 ml",
        "10 ug VC + 1,8 mg of enzyme / 100 ml",
        "10 ug VC + 1,8 mg of enzyme / 100 ml",
        "10 ug VC + 1,8 mg of enzyme / 100 ml",
        "10 ug VC + 1,8 mg of enzyme / 100 ml",
        "10 ug VC + 1,8 mg of enzyme / 100 ml",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water + VC (10 ul) + 1,8 mg enzyme",
        "water + VC (10 ul) + 1,8 mg enzyme",
        "water + VC (10 ul) + 1,8 mg enzyme",
        "water + VC (10 ul) + 1,8 mg enzyme",
        "water + VC (10 ul) + 1,8 mg enzyme",
        "water + VC (10 ul) + 1,8 mg enzyme",
        "water + VC (10 ul) + 1,8 mg enzyme",
        "water + VC (10 ul) + 1,8 mg enzyme",
        "water + VC (10 ul) + 1,8 mg enzyme",
        "water + VC (10 ul) + 1,8 mg enzyme",
        "water + VC (10 ul) + 1,8 mg enzyme",
        "water + VC (10 ul) + 1,8 mg enzyme",
        "water + VC (10 ul) + 1,8 mg enzyme",
        "water + VC (10 ul) + 0,18 mg enzyme",
        "water + VC (10 ul) + 0,18 mg enzyme",
        "water + VC (10 ul) + 0,18 mg enzyme",
        "water + VC (10 ul) + 0,18 mg enzyme",
        "water + VC (10 ul) + 0,18 mg enzyme",
        "water + VC (10 ul) + 0,18 mg enzyme",
        "water + VC (10 ul) + 0,18 mg enzyme",
        "water + VC (10 ul) + 0,18 mg enzyme",
        "water + VC (10 ul) + 0,18 mg enzyme",
        "water + VC (10 ul) + 0,18 mg enzyme",
        "water + VC (10 ul) + 0,18 mg enzyme",
        "water + VC (10 ul) + 0,18 mg enzyme",
        "water",
        "water",
        "water + VC (1 ul / 2.5 ml)",
        "water + VC (1 ul / 2.5 ml)",
        "water + VC (1 ul / 2.5 ml)",
        "water + VC (1 ul / 2.5 ml)",
        "water + VC (1 ul / 2.5 ml)",
        "water + VC (1 ul / 2.5 ml)",
        "water + VC (10 ul / 2.5 ml)",
        "water + VC (10 ul / 2.5 ml)",
        "water + VC (10 ul / 2.5 ml)",
        "water + VC (10 ul / 2.5 ml)",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "10 ul / 2.5 ml",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "<No sample name>",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water + VC (10 ul / 100 ml water)",
        "water + VC (10 ul / 100 ml water)",
        "water + VC (10 ul / 100 ml water)",
        "water + VC (10 ul / 100 ml water)",
        "water + VC (10 ul / 100 ml water)",
        "water",
        "water",
        "water + VC (1 ul / 2.5 ml)",
        "water + VC (1 ul / 2.5 ml)",
        "water + VC (1 ul / 2.5 ml)",
        "water + enzyme (0.18 mg / 100 ml water)",
        "water + enzyme (0.18 mg / 100 ml water)",
        "water + enzyme (0.18 mg / 100 ml water)",
        "water + enzyme (0.18 mg / 100 ml water)",
        "water + enzyme (0.18 mg / 100 ml water)",
        "water + enzyme (0.18 mg / 100 ml water)",
        "water + enzyme (0.18 mg / 100 ml water)",
        "water + enzyme (0.18 mg / 100 ml water) + VC (10 ul / )",
        "water + enzyme (0.18 mg / 100 ml water) + VC (10 ul / )",
        "water + enzyme (0.18 mg / 100 ml water) + VC (10 ul / )",
        "water + enzyme (0.18 mg / 100 ml water) + VC (10 ul / )",
        "water + enzyme (0.18 mg / 100 ml water) + VC (10 ul / )",
        "water + enzyme (0.18 mg / 100 ml water) + VC (10 ul / )",
        "water + enzyme (0.18 mg / 100 ml water) + VC (10 ul / )",
        "water + enzyme (0.18 mg / 100 ml water) + VC (10 ul / )",
        "water + enzyme (0.18 mg / 100 ml water) + VC (10 ul / )",
        "water + enzyme (0.18 mg / 100 ml water) + VC (10 ul / )",
        "water + enzyme (0.18 mg / 100 ml water) + VC (10 ul / )",
        "<No sample name>",
        "<No sample name>",
        "<No sample name>",
        "water + enzyme (0.18 mg / 100 ml water) old",
        "water + enzyme (0.18 mg / 100 ml water) old",
        "water + enzyme (0.18 mg / 100 ml water) old",
        "water + enzyme (0.18 mg / 100 ml water) old",
        "water + enzyme (0.18 mg / 100 ml water) old",
        "water + enzyme (0.18 mg / 100 ml water) old",
        "water + enzyme (0.18 mg / 100 ml water) old + VC 10ul",
        "water + enzyme (0.18 mg / 100 ml water) old + VC 10u",
        "water + enzyme (0.18 mg / 100 ml water) old + VC 10u",
        "water + enzyme (0.18 mg / 100 ml water) old + VC 10u",
        "water + enzyme (0.18 mg / 100 ml water) old + VC 10u",
        "water + enzyme (0.18 mg / 100 ml water) old + VC 10u",
        "water + enzyme (0.18 mg / 100 ml water) old + VC 10u",
        "water + enzyme (0.18 mg / 100 ml water) old + VC 10u",
        "water + enzyme (0.18 mg / 100 ml water) old + VC 10u",
        "water",
        "water",
        "water",
        "solution (VC 10ul + 1.8 mg enzyme)/100 ml water",
        "solution (VC 10ul + 1.8 mg enzyme)/100 ml water",
        "solution (VC 10ul + 1.8 mg enzyme)/100 ml water",
        "solution (VC 10ul + 1.8 mg enzyme)/100 ml water",
        "solution (VC 10ul + 1.8 mg enzyme)/100 ml water",
        "solution (VC 10ul + 1.8 mg enzyme)/100 ml water",
        "solution (VC 10ul + 1.8 mg enzyme)/100 ml water",
        "solution (VC 10ul + 1.8 mg enzyme)/100 ml water",
        "solution (VC 10ul + 1.8 mg enzyme)/100 ml water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "enzyme + water",
        "enzyme + water",
        "enzyme + water",
        "enzyme + water",
        "enzyme + water + VC",
        "enzyme + water + VC",
        "enzyme + water",
        "enzyme + water + VC",
        "enzyme + water + VC",
        "enzyme + water + VC",
        "enzyme + water + VC",
        "enzyme + water + VC",
        "enzyme + water + VC",
        "enzyme + water + VC",
        "enzyme + water + VC",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water + enzyme",
        "water + enzyme",
        "water + enzyme",
        "water + VC (10 ul / 3 ml water)",
        "water + VC (10 ul / 3 ml water)",
        "water + VC (10 ul / 3 ml water)",
        "water + VC (10 ul / 3 ml water)",
        "water + VC (10 ul / 3 ml water)",
        "water + VC (10 ul / 1.5 ml water) + enzyme 1 ml water",
        "water + VC (10 ul / 1.5 ml water) + enzyme 1 ml water",
        "water + VC (10 ul / 1.5 ml water) + enzyme 1 ml water",
        "water + VC (10 ul / 1.5 ml water) + enzyme 1 ml water",
        "water + VC (10 ul / 1.5 ml water) + enzyme 1 ml water",
        "water + VC (10 ul / 1.5 ml water) + enzyme 1 ml water",
        "water + VC (10 ul / 1.5 ml water) + enzyme 1 ml water",
        "water + VC (10 ul / 1.5 ml water) + enzyme 1 ml water",
        "water + VC (10 ul / 1.5 ml water) + enzyme 1 ml water",
        "water + VC (10 ul / 1.5 ml water) + enzyme 1 ml water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water + VC 20 ul",
        "water + VC 20 ul",
        "water + VC 20 ul",
        "water + VC 20 ul",
        "water + VC 20 ul",
        "water + VC 20 ul",
        "water + VC 20 ul",
        "water + VC 20 ul",
        "water + VC 20 ul",
        "water + VC 20 ul",
        "water + VC 20 ul",
        "water + VC 20 ul",
        "water + VC 20 ul",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water + enzymes + VC ratio 1:6",
        "water",
        "water (new reference)",
        "water (new reference)",
        "water (new reference)",
        "water (new reference)",
        "water (new reference)",
        "water (new reference)",
        "water (new reference)",
        "water (new reference)",
        "water (new reference)",
        "water (new reference)",
        "water (new reference)",
        "water (new reference)",
        "water (new reference)",
        "water + Methanol 20 ul",
        "water + Methanol 20 ul",
        "water + Methanol 20 ul",
        "water + Methanol 20 ul",
        "water + Methanol 20 ul",
        "water + Methanol 20 ul",
        "water + Methanol 20 ul",
        "water + Methanol 20 ul",
        "water + Methanol 20 ul + enzyme 0.27 ul",
        "water + Methanol 20 ul + enzyme 0.27 ul",
        "water + Methanol 20 ul + enzyme 0.27 ul",
        "water + Methanol 20 ul + enzyme 0.27 ul",
        "water + Methanol 20 ul + enzyme 0.27 ul",
        "water + Methanol 20 ul + enzyme 0.27 ul",
        "water + Methanol 20 ul + enzyme 0.27 ul",
        "water + Methanol 20 ul + enzyme 0.27 ul",
        "water + Methanol 20 ul + enzyme 0.27 ul",
        "water + Methanol 20 ul + enzyme 0.27 ul",
        "water + Methanol 20 ul + enzyme 0.27 ul",
        "water + Methanol 20 ul + enzyme 0.27 ul",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC + enzyme",
        "water + VC + enzyme",
        "water + VC + enzyme",
        "water + VC + enzyme",
        "water + VC + enzyme",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC + enzyme",
        "water + VC",
        "water + VC + enzyme",
        "water + VC",
        "water + VC + enzyme",
        "water + VC",
        "water + VC + enzyme",
        "water + VC",
        "water + VC",
        "water + VC + enzyme",
        "water + VC",
        "water + VC",
        "water + VC + enzyme",
        "water + VC + enzyme",
        "water + VC + enzyme",
        "water + VC + enzyme",
        "water + VC + enzyme",
        "water + VC + enzyme",
        "water + VC + enzyme",
        "water + VC + enzyme",
        "water + VC + enzyme",
        "water + VC + enzyme",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water + VC",
        "water",
        "water + VC",
        "water",
        "water + vc",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME",
        "water + VC + ENZYME"
      ]
    },
    {
      "projectName": "Enzyme + VC + Water 02.05.2022",
      "samplesNames": [
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water + VC (10 ul/cuvette)",
        "water + VC (10 ul/cuvette)",
        "water + VC (10 ul/cuvette)",
        "water + VC (10 ul/cuvette)",
        "water + VC (10 ul/cuvette)",
        "water + VC (10 ul/cuvette)",
        "water + VC (10 ul/cuvette)",
        "water + VC (10 ul/cuvette)",
        "water + VC (10 ul/cuvette)",
        "water + VC (10 ul/cuvette)",
        "water + VC (10 ul/cuvette)",
        "water + VC (10 ul/cuvette)",
        "water + VC (10 ul/cuvette)",
        "water + VC (10 ul/cuvette)",
        "water + VC (10 ul/cuvette)",
        "water + VC (10 ul/cuvette)",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water",
        "water",
        "water",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water",
        "water",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water",
        "water",
        "water",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water",
        "water",
        "water + Enzyme 0,227 ul",
        "water + Enzyme 0,227 ul",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water + Enzyme 0,227 ul",
        "water + Enzyme 0,227 ul",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC + Enzyme",
        "water + VC + Enzyme",
        "water + VC + Enzyme",
        "water + VC + Enzyme",
        "water + VC + Enzyme",
        "water",
        "water",
        "water + VC + Enzyme",
        "water + VC + Enzyme",
        "water",
        "water + VC + Enzyme",
        "water",
        "water",
        "water + VC",
        "water + VC + Enzyme",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC + Enzyme",
        "water + VC + Enzyme",
        "water + VC + Enzyme",
        "water + VC + Enzyme",
        "water + VC + Enzyme",
        "water + VC + Enzyme",
        "water + VC + Enzyme",
        "water + VC + Enzyme",
        "water + VC + Enzyme",
        "water + VC + Enzyme",
        "water + VC (10 ul/cuvette) + Enzyme 0,227 ul",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water + enzyme",
        "water + enzyme",
        "water + enzyme",
        "water + enzyme",
        "water + enzyme",
        "water + enzyme",
        "water + enzyme",
        "methanol",
        "water",
        "water",
        "water",
        "water + VC",
        "water + VC",
        "water + VC",
        "water + VC",
        "WATER + VC",
        "water + vc +enzyme",
        "water + vc +enzyme",
        "water + vc +enzyme",
        "water + vc +enzyme",
        "water + vc +enzyme"
      ]
    },
    {
      "projectName": "Enzyme + VC + Water 19.05.2022",
      "samplesNames": [
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water + VC 15 ug + enzyme",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water + VC 20 ug + enzyme",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water - no good quality",
        "water - no good quality",
        "water - no good quality",
        "water - no good quality",
        "water - no good quality",
        "water - no good quality",
        "water - no good quality",
        "water - no good quality",
        "water - no good quality",
        "water - no good quality",
        "water - no good quality",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water + VC 17 ug/2 ml",
        "water + VC 17 ug/2 ml",
        "water + VC 17 ug/2 ml",
        "water + VC 17 ug/2 ml",
        "water + VC 17 ug/2 ml",
        "water + VC 17 ug/2 ml",
        "water + VC 17 ug/2 ml",
        "water + VC 17 ug/2 ml",
        "water + VC 17 ug/2 ml",
        "water + VC 17 ug/2 ml",
        "water + VC 17 ug/2 ml + enzyme",
        "water + VC 17 ug/2 ml + enzyme",
        "water + VC 17 ug/2 ml + enzyme",
        "water + VC 17 ug/2 ml + enzyme",
        "water + VC 17 ug/2 ml + enzyme",
        "water + VC 17 ug/2 ml + enzyme",
        "water + VC 17 ug/2 ml + enzyme",
        "water + VC 17 ug/2 ml + enzyme",
        "water + VC 17 ug/2 ml + enzyme",
        "water + VC 17 ug/2 ml + enzyme",
        "water + VC 17 ug/2 ml + enzyme",
        "water + VC 17 ug/2 ml + enzyme",
        "water + VC 17 ug/2 ml + enzyme",
        "water + VC 17 ug/2 ml + enzyme",
        "water + VC 17 ug/2 ml + enzyme",
        "water + VC 17 ug/2 ml + enzyme"
      ]
    },
    {
      "projectName": "Enzyme + VC + Water 27.05.2022",
      "samplesNames": [
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water + VC 20 ul",
        "water + VC 18 ul",
        "water + VC 20 ul",
        "water + VC 18 ul",
        "water + VC 20 ul",
        "water + VC 18 ul",
        "water + VC 20 ul",
        "water + VC 18 ul",
        "water + VC 20 ul",
        "water + VC 18 ul",
        "water + VC 20 ul",
        "water + VC 18 ul",
        "water + VC 20 ul",
        "water + VC 18 ul",
        "water + VC 18 ul",
        "water + VC 20 ul",
        "water + VC 20 ul + enzyme",
        "water + VC 18 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 18 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 18 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 18 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 18 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 18 ul + enzyme - bad quality",
        "water + VC 20 ul + enzyme",
        "water + VC 18 ul + enzyme - bad quality",
        "water + VC 20 ul + enzyme",
        "water + VC 18 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 18 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 18 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 18 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 18 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 18 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 18 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 18 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 18 ul + enzyme",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water",
        "water + VC 15 ul",
        "water + VC 20 ul",
        "water + VC 15 ul",
        "water + VC 20 ul",
        "water + VC 15 ul",
        "water + VC 20 ul",
        "water + VC 15 ul",
        "water + VC 20 ul",
        "water + VC 15 ul",
        "water + VC 20 ul",
        "water + VC 15 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 15 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 15 ul + enzyme",
        "water + VC 20ul + enzyme",
        "water + VC 15 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 15 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 15 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 15 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 15 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 15 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 15 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 15 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 15 ul + enzyme",
        "water + VC 20 ul + enzyme",
        "water + VC 15 ul + enzyme",
        "Water reference 2 ml",
        "Water + VC + Enzime nr1",
        "Water + VC + enzyme nr2"
      ]
    }
  ],
  "spectra": {
    "reference_B": [
      700.0755591922143,
      0.339284117527
    ],
    "sample_A": [
      338.8552397614145,
      0.11620434569284283
    ],
    "sample_B": [
      404.8550320327822,
      0.20487922392132896
    ],
    "sample_D": "Target wavelength out of interval!"
  }
}